apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: redlock-delete
    component: redlock-delete
  name: redlock-delete
spec:
  replicas: 1
  selector:
    matchLabels:
      application: redlock-delete
      component: redlock-delete
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: redlock-delete
        component: redlock-delete
        redeploy: '1'
    spec:
      containers:
        - name: redlock-delete
          image: redlock-delete
          imagePullPolicy: IfNotPresent
          env:
          - name: REDIS_SERVER_IP
            value: "redis-server"
          ports:
          - name: redlock-delete
            containerPort: 3000
            protocol: TCP