server:
  port: 9192
spring:
  kafka:
    bootstrap-servers: sulky-01.srvs.cloudkafka.com:9094,sulky-02.srvs.cloudkafka.com:9094,sulky-03.srvs.cloudkafka.com:9094
    jaas:
      enabled: true
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="ljk4y5xr" password="ySTNY76FFBiAW4LEiGgnn5GQhhJ4wHww";
    consumer:
      group-id: cloudkarafka-redlock
      auto-offset-reset: latest

  cloud:
    stream:
      kafka:
        binder:
          replication-factor: 1
      function:
        definition: orderPurchaseEventPublisher;cacheDataSavedEventPublisher;
      bindings:
        orderPurchaseEventPublisher-out-0:
          destination: ljk4y5xr-orders
        cacheDataSavedEventPublisher-out-0:
          destination: ljk4y5xr-cache
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
    maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: true
