apiVersion: v1
kind: Service
metadata:
  name: redlock-write
  labels:
    application: redlock-write
    component: redlock-write
spec:
  type: NodePort
  selector:
    application: redlock-write
    component: redlock-write
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000